Repository nest-desktop/nest-desktop, pull requests merged in 2021-07, with the labels that each got.

#90 Params
  src/assets/projects/current-input.json
  src/assets/projects/neuron-spike-response.json
  src/assets/projects/spatial-neurons.json
  src/assets/projects/spatial-spike-activity.json
  src/assets/projects/spike-activity.json
  src/assets/projects/spike-input.json
  src/core/node/node.ts
  src/core/parameter/modelParameter.ts
  src/core/parameter/parameter.ts
Labels: bug

#91 Add link to official model directory of nest-simulator
  src/components/model/ModelDocumentation.vue
Labels: enhancement

#92 Restructure code files and smaller buttons in menu
  src/components/connection/ConnectionMenu.vue
  src/components/connection/ConnectionParamEdit.vue
  src/components/connection/ConnectionParamSelect.vue
  src/components/network/NetworkGraph.vue
  src/components/network/NetworkGraphToolbar.vue
  src/components/network/NetworkParamEdit.vue
  src/components/network/NodeModelSelect.vue
  src/components/node/NodeChip.vue
  src/components/node/NodeMenu.vue
  src/components/node/NodeModelSelect.vue
  src/components/node/NodeParamEdit.vue
  src/components/node/NodePosition.vue
  src/components/node/NodePositionTitle.vue
  src/components/project/ProjectLabBook.vue
  src/components/project/ProjectMenu.vue
  src/components/project/ProjectsMenu.vue
  src/core/connection/connection.ts
  src/views/Project.vue
Labels: enhancement

#93 NetworkGraph: Add plus symbol to the connector
  src/components/network/NetworkGraph.vue
  src/core/network/networkGraph.ts
Labels: enhancement

#98 Node menu snackbar button
  src/components/activity/ActivityGraph.vue
  src/components/network/NetworkGraph.vue
  src/components/node/NodeMenu.vue
Labels: bug

#97 Upgrade node modules
  package.json
  yarn.lock
Labels: maintenance

#101 Prevent endless reloading
  src/App.vue
  src/assets/config/App.json
  src/registerServiceWorker.ts
  src/views/Settings.vue
  vue.config.js
Labels: bug

#106 Remove temporary navigation
  src/App.vue
  src/components/navigation/NavigationTemporary.vue
Labels: maintenance

#105 Optimize initializing activity graph
  src/core/activity/activityGraph.ts
  src/core/connection/connection.ts
  src/core/network/network.ts
  src/core/node/node.ts
  src/core/project/project.ts
Labels: bug

#104 No need to format parameter values to float.
  docker-compose.yml
  src/assets/config/Connection.json
  src/assets/models/spike_generator.json
  src/assets/models/step_current_generator.json
  src/components/parameter/ParameterEdit.vue
  src/core/code.ts
  src/core/connection/connectionCode.ts
  src/core/connection/synapseCode.ts
  src/core/model/modelCode.ts
  src/core/network/networkCode.ts
  src/core/node/nodeCode.ts
  src/core/node/nodeSpatial.ts
  src/core/parameter/parameter.ts
  src/core/parameter/valueGenerator.ts
  src/core/project/projectCode.ts
  src/core/simulation/simulationCode.ts
Labels: enhancement

#99 Restructure network graph
  src/components/network/NetworkGraph.vue
  src/components/node/NodeChip.vue
  src/core/connection/connectionGraph.ts
  src/core/network/networkGraph.ts
  src/core/node/nodeGraph.ts
Labels: maintenance

#109 Upload project from GitHub
  package.json
  src/components/project/ProjectMenu.vue
  src/components/project/ProjectsDialog.vue
  src/components/project/ProjectsImportDialog.vue
  src/components/project/ProjectsMenu.vue
  src/components/project/ProjectsUploadDialog.vue
  yarn.lock
Labels: enhancement
