Repository nest-desktop/nest-desktop, pull requests merged in 2021-12, with the labels that each got.

#166 Add tag for synapse and show title
  src/components/model/ModelDocumentation.vue
Labels: maintenance

#171 Page title
  public/index.html
  vue.config.js
Labels: enhancement

#167 Change config for docs
  docs/conf.py
Labels: documentation

#170 Operator to null/undefined
  src/components/model/ModelEditor.vue
  src/components/parameter/ParameterEdit.vue
  src/core/activity/activityAnimation/activityAnimationScenes/activityAnimationSceneBox.ts
  src/core/activity/activityAnimation/activityAnimationScenes/activityAnimationSceneSphere.ts
  src/core/activity/activityChart/activityChartPanelModel.ts
  src/core/activity/analogSignalActivity.ts
  src/core/common/database.ts
  src/core/connection/connection.ts
  src/core/connection/connectionState.ts
  src/core/model/model.ts
  src/core/network/networkGraph/networkGraphDragline.ts
  src/core/network/networkState.ts
  src/core/node/node.ts
  src/core/node/nodeSlice.ts
  src/core/node/nodeState.ts
  src/core/project/projectUpgrade.ts
  src/core/synapse/synapse.ts
  src/views/Project.vue
Labels: maintenance

#172 Node modules
  package-lock.json
  package.json
  yarn.lock
Labels: maintenance

#165 Add files for docker image on gitlab-ci
  .gitlab-ci-docker/Dockerfile
  .gitlab-ci-docker/nginx-default.conf
Labels: enhancement

#169 Change version to beta
  .gitlab-ci.yml
  nest_desktop/__init__.py
  package.json
Labels: maintenance

#173 Update network graph when a new project is loaded.
  src/components/network/NetworkEditor.vue
  src/core/network/networkGraph/networkGraph.ts
  src/core/node/node.ts
  src/core/node/nodeGraph/nodeGraph.ts
  src/core/node/nodeState.ts
  src/core/project/project.ts
  src/core/project/projectStore.ts
  src/core/project/projectView.ts
  src/views/Project.vue
Labels: bug

#179 vue.config.js: Optimize compile performance
  vue.config.js
Labels: enhancement

#180 vue.config.js: Try different settings for core count
  vue.config.js
Labels: enhancement

#174 Restyle card border in controller
  src/components/activity/activityChart/ActivityChartController.vue
  src/components/activity/activityStats/ActivityStats.vue
  src/components/connection/ConnectionParamEdit.vue
  src/components/network/NetworkParamEdit.vue
  src/components/project/ProjectLabBook.vue
  src/components/simulation/SimulationKernel.vue
Labels: maintenance

#175 Add slider for time in animation controller
  src/components/activity/activityAnimation/ActivityAnimationController.vue
  src/components/parameter/ParameterEdit.vue
Labels: enhancement

#177 Node Slice to JSON
  src/core/connection/connection.ts
  src/core/node/nodeSlice.ts
Labels: enhancement

#168 Add doc for insite
  docs/contents.rst
  docs/user/index.rst
  docs/user/usage-insite.rst
Labels: documentation

#188 Correct url for spikedetectors in insite
  src/core/project/project.ts
Labels: maintenance

#187 Merge doc to dev
  .gitlab-ci.yml
  README.md
  docs/_static/img/screenshots/code-editor.png
  docs/_static/img/screenshots/kernel-settings.png
  docs/conf.py
  docs/contents.rst
  docs/index.rst
  docs/lecturer/doctorate/networks-decision-making.rst
  docs/user/index.rst
  docs/user/troubleshooting.rst
  docs/user/usage-insite.rst
  docs/user/usage.rst
  nest_desktop/__init__.py
  package.json
Labels: documentation, maintenance

#176 Update command
  bin/nest-desktop
Labels: maintenance

#181 Dark mode
  src/components/AppDetails.vue
  src/components/activity/activityStats/ActivityStats.vue
  src/components/connection/ConnectionMenu.vue
  src/components/icons/NESTIcon.vue
  src/components/navigation/Navigation.vue
  src/components/network/NetworkEditor.vue
  src/components/network/NetworkParamEdit.vue
  src/components/node/NodeMenu.vue
  src/components/node/NodePopMenu.vue
  src/components/parameter/ParameterEdit.vue
  src/components/project/ProjectLabBook.vue
  src/views/Settings.vue
Labels: enhancement

#182 Node modules
  package-lock.json
  package.json
  yarn.lock
Labels: maintenance

#185 Use shortHash or shortId
  src/components/connection/ConnectionMenu.vue
  src/components/network/NetworkParamEdit.vue
  src/components/node/NodeModelSelect.vue
  src/components/simulation/SimulationCodeEditor.vue
  src/components/synapse/SynapseModelSelect.vue
  src/core/connection/connection.ts
  src/core/connection/connectionGraph/connectionGraph.ts
  src/core/node/node.ts
  src/core/project/project.ts
  src/core/project/projectCode.ts
Labels: enhancement

#186 Gitlab CI
  .github/workflows/ebrains-push.yml
  .gitlab-ci.yml
  vue.config.js
Labels: enhancement

#189 Remove flat from v-btn
  src/components/simulation/SimulationKernel.vue
Labels: maintenance

#190 Update docs in about
  README.md
  docs/_static/img/screenshots/start-page.png
  docs/about/abstract.rst
  docs/about/history.rst
  docs/about/releases.rst
Labels: documentation

#192 Upgrade node modules; remove console.log in vue.config
  package.json
  vue.config.js
  yarn.lock
Labels: maintenance

#193 Remove dat.gui
  package.json
  src/core/activity/activityAnimation/activityAnimationScene.ts
  yarn.lock
Labels: maintenance

#191 Big Bang 7: Optimize dark mode
  src/App.vue
  src/assets/config/App.json
  src/assets/config/ProjectView.json
  src/assets/img/logo/ebrains-logo-white-text.svg
  src/assets/img/logo/eu-logo-white-text.png
  src/assets/img/logo/hbp-logo-white-text.png
  src/assets/img/logo/nest-desktop-logo-white.svg
  src/assets/img/logo/nest-desktop-logo.png
  src/assets/img/logo/nest-desktop-logo.svg
  src/components/activity/activityAnimation/ActivityAnimationController.vue
  src/components/activity/activityStats/ActivityStats.vue
  src/components/connection/ConnectionMenu.vue
  src/components/connection/ConnectionParamSelect.vue
  src/components/icons/NESTIcon.vue
  src/components/navigation/ModelNavList.vue
  src/components/navigation/Navigation.vue
  src/components/navigation/ProjectNavList.vue
  src/components/network/NetworkEditor.vue
  src/components/network/NetworkParamEdit.vue
  src/components/node/NodeMenu.vue
  src/components/node/NodePopMenu.vue
  src/components/node/NodePosition.vue
  src/components/parameter/ParameterEdit.vue
  src/components/project/ProjectLabBook.vue
  src/components/project/ProjectRawData.vue
  src/components/setting/InsiteAccessConfig.vue
  src/components/setting/NESTSimulatorConfig.vue
  src/components/simulation/SimulationButton.vue
  src/components/simulation/SimulationCodeEditor.vue
  src/components/simulation/SimulationKernel.vue
  src/components/synapse/SynapseParamSelect.vue
  src/core/activity/activityAnimation/activityAnimationScene.ts
  src/core/activity/activityChart/activityChartGraph.ts
  src/core/activity/activityChart/activityChartPanelModels/CVISIHistogramModel.ts
  src/core/activity/activityChart/activityChartPanelModels/analogSignalHistogramModel.ts
  src/core/activity/activityChart/activityChartPanelModels/analogSignalPlotModel.ts
  src/core/activity/activityChart/activityChartPanelModels/interSpikeIntervalHistogramModel.ts
  src/core/activity/activityChart/activityChartPanelModels/spikeSendersHistogramModel.ts
  src/core/activity/activityChart/activityChartPanelModels/spikeTimesHistogramModel.ts
  src/core/app.ts
  src/core/model/modelView.ts
  src/core/network/networkGraph/networkGraphGrid.ts
  src/core/network/networkGraph/networkGraphNodeAddPanel.ts
  src/core/network/networkGraph/networkGraphWorkspace.ts
  src/core/network/networkState.ts
  src/core/node/node.ts
  src/core/node/nodeGraph/nodeGraphConnector.ts
  src/core/node/nodeGraph/nodeGraphShape.ts
  src/core/project/projectView.ts
  src/plugins/codemirror.ts
  src/plugins/vuetify.ts
  src/views/AppInfo.vue
  src/views/Model.vue
  src/views/Project.vue
  src/views/Settings.vue
Labels: enhancement

#195 Only slice projectId if existed.
  src/core/project/projectView.ts
Labels: bug
