Repository nest-desktop/nest-desktop, pull requests merged in 2021-09, with the labels that each got.

#121 Upgrade node modules
  package.json
  yarn.lock
Labels: maintenance

#124 Doc abstract link
  docs/about/abstract.rst
Labels: documentation

#122 Sidebars: Optimize view
  src/components/navigation/Navigation.vue
  src/views/Home.vue
  src/views/Project.vue
Labels: enhancement

#125 Fix code generation for connection specifications.
  src/core/connection/connectionCode.ts
Labels: bug

#127 Fix transform network-graph after sidebar closing/opening
  src/components/network/NetworkGraph.vue
Labels: bug

#126 Extend model and parameter views
  src/App.vue
  src/assets/models/hh_psc_alpha.json
  src/assets/models/multimeter.json
  src/assets/models/voltmeter.json
  src/components/model/ModelDocumentation.vue
  src/components/model/ModelEditor.vue
  src/components/model/ModelExplorer.vue
  src/components/network/NetworkGraphToolbar.vue
  src/components/network/NetworkParamEdit.vue
  src/components/node/NodeModelSelect.vue
  src/components/node/NodeParamEdit.vue
  src/components/parameter/ParameterEdit.vue
  src/components/simulation/SimulationKernel.vue
  src/core/model/model.ts
  src/core/node/node.ts
  src/core/node/nodeView.ts
  src/core/parameter/modelParameter.ts
  src/core/parameter/parameter.ts
  src/views/Model.vue
Labels: enhancement

#128 Increase width for network controller
  src/components/network/NetworkParamEdit.vue
  src/views/Project.vue
Labels: bug

#135 Node modules
  package.json
  src/components/model/ModelExplorer.vue
  src/components/network/NetworkParamEdit.vue
  yarn.lock
Labels: maintenance
