Repository nest-desktop/nest-desktop, pull requests merged in 2021-08, with the labels that each got.

#110 About.vue: Optimize mail text with debug information
  package.json
  src/components/About.vue
Labels: enhancement

#115 Rename NEST Simulator
  LICENSE
  README.md
  bin/nest-desktop
  docker-compose.yml
  singularity/nest-desktop-app.def
  singularity/nest-desktop-dev.def
  singularity/nest-desktop-prod.def
Labels: maintenance

#117 Doc installation guide (II)
  LICENSE
  README.md
  docs/_static/img/icons/apple.svg
  docs/_static/img/icons/linux.svg
  docs/_static/img/icons/windows.svg
  docs/_static/img/installation-guide.png
  docs/about/abstract.rst
  docs/conf.py
  docs/contents.rst
  docs/deployer/deploy-docker.rst
  docs/developer/development.rst
  docs/developer/semantic-version.rst
  docs/user/index.rst
  docs/user/setup.rst
  docs/user/troubleshooting.rst
  docs/user/use-ebrains.rst
Labels: documentation
