Repository nest-desktop/nest-desktop, pull requests merged in 2022-08, with the labels that each got.

#399 Network graph cleanup
  src/assets/config/Connection.json
  src/assets/config/NetworkGraph.json
  src/assets/config/Node.json
  src/core/connection/connectionGraph/connectionGraphPath.ts
Labels: maintenance

#405 Fix minor flaws
  docs/developer/coding-conventions.rst
  docs/reference/sections/project.rst
Labels: documentation

#396 Sort activities by recorder unit IDs in Insite mode
  src/core/activity/activity.ts
  src/core/activity/analogSignalActivity.ts
  src/core/activity/spikeActivity.ts
  src/core/project/insite/insite.ts
Labels: bug
