Repository nest-desktop/nest-desktop, pull requests merged in 2022-12, with the labels that each got.

#461 Bump to pre-release
  package.json
  public/config/app.json
  public/index.html
Labels: maintenance

#465 Better config and add icons for PWA
  public/favicon.ico
  public/img/icons/android-chrome-maskable-192x192.png
  public/img/icons/android-chrome-maskable-512x512.png
  public/img/icons/apple-touch-icon-120x120.png
  public/img/icons/apple-touch-icon-180x180.png
  public/img/icons/apple-touch-icon-60x60.png
  public/img/icons/apple-touch-icon-76x76.png
  public/img/icons/apple-touch-icon.png
  public/img/icons/safari-pinned-tab.svg
  public/img/nest-desktop-icon.svg
  public/index.html
  public/manifest.json
  vue.config.js
Labels: enhancement

#462 Add Security policy
  SECURITY.md
Labels: enhancement

#467 Upgrade node modules
  package.json
  yarn.lock
Labels: dependencies

#468 Fetch models from NEST
  src/core/model/modelStore.ts
Labels: maintenance

#464 Fix displacement of network history and simulation button
  src/components/network/NetworkHistory.vue
  src/components/project/ProjectBar.vue
  src/components/simulation/SimulationButton.vue
  src/views/Project.vue
Labels: bug

#469 Fix url to error messages
  src/core/simulation/simulation.ts
Labels: bug

#470 Add "Select all"/"Unselect all" buttons to model/project export and delete views
  src/components/dialog/ModelsDialog.vue
  src/components/dialog/ProjectsDialog.vue
Labels: enhancement

#471 Improve titles
  src/components/navigation/ModelNavList.vue
  src/components/systembar/BackendStatus.vue
  src/components/systembar/ModelsMenu.vue
  src/components/systembar/ProjectsMenu.vue
Labels: enhancement

#466 Fix redirecting error when nav list is empty
  src/core/model/modelStore.ts
  src/core/model/modelView.ts
  src/core/project/projectStore.ts
  src/core/project/projectView.ts
Labels: bug

#472 Unselect nodes and connections when clicking on element type
  src/components/network/NetworkParamToolbar.vue
Labels: bug

#473 Fix activity controller
  src/components/parameter/ParameterEdit.vue
  src/core/activity/activityChart/activityChartPanelModels/senderCVISIPlotModel.ts
  src/core/activity/activityChart/activityChartPanelModels/senderMeanISIPlotModel.ts
  src/core/activity/activityChart/activityChartPanelModels/senderSpikeCountPlotModel.ts
Labels: bug

#474 Rotate icon
  src/views/Project.vue
Labels: bug

#482 Add dot for prelease
  .gitlab-ci.yml
Labels: maintenance

#483 Node modules
  package.json
  yarn.lock
Labels: dependencies

#485 Fix bug of value inrement/decrement
  src/components/parameter/ParameterEdit.vue
Labels: bug

#486 No help popup in model view
  src/components/activity/ActivityGraph.vue
  src/views/Project.vue
Labels: feature regression

#487 Add type for connection
  src/core/connection/connection.ts
Labels: bug

#488 Use default weight from model
  src/core/synapse/synapse.ts
Labels: bug

#489 Better formatting for simulation code
  src/core/node/nodeSpatial/freePositions.code
Labels: bug

#490 Cleanup code
  src/core/parameter/parameter.ts
Labels: maintenance

#491 Cleanup simulation code
  src/components/simulation/SimulationCodeEditor.vue
  src/core/simulation/simulationCode.ts
  src/core/simulation/simulationCodes/nest-master.code
  src/core/simulation/simulationCodes/nest-v3.0.code
  src/core/simulation/simulationCodes/nest-v3.1.code
  src/core/simulation/simulationCodes/nest-v3.2.code
  src/core/simulation/simulationCodes/nest-v3.3.code
  src/core/simulation/simulationCodes/nest-v3.4.code
Labels: maintenance
