Repository nest-desktop/nest-desktop, pull requests merged in 2022-11, with the labels that each got.

#411 Small bug fixes
  src/core/model/model.ts
  src/core/model/modelStore.ts
  src/core/model/modelView.ts
  src/core/node/nodeCompartment/nodeCompartment.ts
  src/core/parameter/valueGenerator.ts
  src/core/project/insite/insite.ts
  src/core/project/project.ts
Labels: bug

#422 Add button to export networkGraph to image file.
  src/components/network/NetworkEditor.vue
  src/components/network/NetworkEditorToolbar.vue
  src/core/network/networkGraph/networkGraph.ts
  src/core/node/nodeGraph/nodeGraphShape.ts
Labels: enhancement

#426 Restructure upgrades
  src/core/project/project.ts
  src/core/project/projectUpgrade.ts
  src/core/upgrades/upgrade_2x_to_30.ts
  src/core/upgrades/upgrade_30_to_31.ts
  src/core/upgrades/upgrade_31_to_32.ts
  src/core/upgrades/upgrade_32_to_33.ts
  src/core/upgrades/upgrades.ts
Labels: maintenance

#428 Fix the bulk deletion of projects
  src/components/dialog/ModelsDialog.vue
  src/components/dialog/ProjectsDialog.vue
  src/core/model/modelDB.ts
  src/core/model/modelStore.ts
  src/core/project/projectDB.ts
  src/core/project/projectStore.ts
  src/core/upgrades/upgrades.ts
Labels: bug

#431 Fix simulation code
  src/components/simulation/SimulationCodeEditor.vue
  src/core/simulation/simulationCodes/nest3.0.code
  src/core/simulation/simulationCodes/nest3.1.code
  src/core/simulation/simulationCodes/nest3.2.code
  src/core/simulation/simulationCodes/nest3.3.code
Labels: bug

#433 Change default port for NEST Server
  src/components/setting/NESTSimulatorConfig.vue
  src/core/app.ts
  src/core/common/backend.ts
  src/main.ts
Labels: maintenance

#440 Fix gitlab CI
  .gitlab-ci.yml
  package.json
Labels: bug

#439 Node modules
  package.json
  yarn.lock
Labels: dependencies

#432 Fix param validation
  src/assets/config/Connection.json
  src/assets/config/Node.json
  src/assets/models/ac_generator.json
  src/assets/models/dc_generator.json
  src/assets/models/hh_psc_alpha.json
  src/assets/models/iaf_cond_alpha.json
  src/assets/models/iaf_psc_alpha.json
  src/assets/models/multimeter.json
  src/assets/models/noise_generator.json
  src/assets/models/parrot_neuron.json
  src/assets/models/poisson_generator.json
  src/assets/models/spike_generator.json
  src/assets/models/spike_recorder.json
  src/assets/models/static_synapse.json
  src/assets/models/step_current_generator.json
  src/assets/models/voltmeter.json
  src/components/network/NetworkParamEdit.vue
  src/components/node/NodePosition.vue
  src/components/parameter/ParameterEdit.vue
  src/components/simulation/SimulationKernel.vue
  src/core/app.ts
Labels: bug

#434 Disable interval backend checking for development
  .env.development
  src/assets/config/App.json
  src/core/app.ts
Labels: maintenance

#436 Cleanup codes
  src/App.vue
  src/components/activity/ActivityGraph.vue
  src/components/activity/activityAnimation/ActivityAnimationGraph.vue
  src/components/dialog/ModelsImportDialog.vue
  src/components/dialog/ProjectsImportDialog.vue
  src/components/simulation/SimulationButton.vue
  src/views/Project.vue
Labels: maintenance

#437 Change location for config file `app.json`
  docker-compose.yml
  docker/entrypoint.sh
  public/config/app.json
  src/main.ts
Labels: maintenance

#442 Fix fetching models from NEST
  src/components/systembar/BackendStatus.vue
Labels: bug

#443 Use environment variable for VERSION
  src/core/app.ts
  src/core/common/config.ts
  src/environments/environment.prod.ts
  src/environments/environment.ts
  vue.config.js
Labels: maintenance

#444 Ask user on leave when some project is changed
  src/App.vue
  src/core/project/projectStore.ts
Labels: enhancement

#445 Node modules
  .eslintrc.js
  babel.config.js
  package.json
  postcss.config.js
  tsconfig.json
  yarn.lock
Labels: dependencies

#446 Change default port
  bin/nest-desktop
  docker-compose.yml
  docker/Dockerfile
  docker/Dockerfile-builder
  docker/nginx-default.conf
  package.json
Labels: maintenance

#448 Cleanup codes and correct rules
  src/assets/models/ac_generator.json
  src/components/CodeMirror.vue
  src/components/parameter/ParameterEdit.vue
  src/core/activity/activityAnimation/activityAnimationScene.ts
Labels: maintenance

#449 Fetch models after backend checks
  src/core/app.ts
Labels: bug

#451 Use virtual scroll for nav list
  src/components/navigation/ModelNavList.vue
  src/components/navigation/ProjectNavList.vue
Labels: enhancement

#452 Remove singularity
  singularity/dev-electron-builder.def
  singularity/dev-node-16-alpine.def
  singularity/doc-sphinx.def
  singularity/prod-snapcraft.def
  singularity/test-ubuntu-20.04.def
  singularity/ubuntu-nest-desktop-dev.def
Labels: maintenance

#454 Add `new project` in menu
  src/components/navigation/ProjectNavList.vue
  src/components/systembar/ProjectsMenu.vue
Labels: enhancement

#453 Remove tooltip
  src/components/activity/activityChart/ActivityChartController.vue
  src/components/model/ModelEditor.vue
  src/components/navigation/Navigation.vue
  src/components/network/NetworkParamToolbar.vue
  src/components/node/NodeParamEdit.vue
  src/components/simulation/SimulationCodeEditor.vue
  src/views/AppInfo.vue
  src/views/AppSettings.vue
  src/views/Model.vue
  src/views/Project.vue
Labels: maintenance

#456 Improve/fix descriptions
  src/components/dialog/ModelsDialog.vue
  src/components/dialog/ProjectsDialog.vue
  src/components/navigation/ModelNavList.vue
  src/components/navigation/ProjectNavList.vue
  src/components/network/NetworkEditorToolbar.vue
Labels: bug

#458 Upgrade node modules
  package.json
  yarn.lock
Labels: dependencies

#457 Increase memory limit of dev server
  vue.config.js
Labels: feature regression
