Repository nest-desktop/nest-desktop, pull requests merged in 2022-01, with the labels that each got.

#194 Wrap long text in doc files
  docs/about/abstract.rst
  docs/about/history.rst
  docs/conf.py
  docs/contents.rst
  docs/deployer/deploy-docker.rst
  docs/deployer/deploy-openstack.rst
  docs/developer/index.rst
  docs/developer/interface-concept.rst
  docs/developer/preparation.rst
  docs/developer/references.rst
  docs/developer/semantic-version.rst
  docs/developer/user-doc.rst
  docs/user/setup.rst
  docs/user/troubleshooting.rst
  docs/user/usage.rst
  docs/user/use-ebrains.rst
Labels: documentation

#199 Rename ProjectRawData to CodeMirror
  src/components/CodeMirror.vue
  src/components/simulation/SimulationCodeEditor.vue
  src/core/project/projectView.ts
  src/views/Project.vue
Labels: maintenance

#201 Fix showing model doc in node menu
  src/components/model/ModelDocumentation.vue
  src/views/Model.vue
Labels: bug

#202 Remove color from button in dialog
  src/components/connection/ConnectionMenu.vue
  src/components/node/NodeMenu.vue
Labels: maintenance

#203 Upgrade node modules
  package.json
  src/components/navigation/Navigation.vue
  yarn.lock
Labels: maintenance

#200 Big Bang 8: Enhance activity graph with node records
  src/App.vue
  src/assets/scss/dat-gui-light-theme.scss
  src/components/activity/activityChart/ActivityChartController.vue
  src/components/activity/activityChart/ActivityChartPanelToolbar.vue
  src/components/activity/activityStats/ActivityStats.vue
  src/components/activity/activityStats/ActivityStatsAnalog.vue
  src/components/network/NetworkParamEdit.vue
  src/components/node/NodeMenu.vue
  src/components/node/NodeParamEdit.vue
  src/components/node/NodePopMenu.vue
  src/components/project/ProjectLabBook.vue
  src/components/simulation/SimulationKernel.vue
  src/core/activity/activity.ts
  src/core/activity/activityAnimation/activityAnimationGraph.ts
  src/core/activity/activityChart/activityChartGraph.ts
  src/core/activity/activityChart/activityChartPanel.ts
  src/core/activity/activityChart/activityChartPanelModel.ts
  src/core/activity/activityChart/activityChartPanelModels/CVISIHistogramModel.ts
  src/core/activity/activityChart/activityChartPanelModels/FICurvePlotModel.ts
  src/core/activity/activityChart/activityChartPanelModels/analogSignalHistogramModel.ts
  src/core/activity/activityChart/activityChartPanelModels/analogSignalPanelModel.ts
  src/core/activity/activityChart/activityChartPanelModels/analogSignalPlotModel.ts
  src/core/activity/activityChart/activityChartPanelModels/inputAnalogSignalPlotModel.ts
  src/core/activity/activityChart/activityChartPanelModels/interSpikeIntervalHistogramModel.ts
  src/core/activity/activityChart/activityChartPanelModels/neuronAnalogSignalPlotModel.ts
  src/core/activity/activityChart/activityChartPanelModels/spikeSendersHistogramModel.ts
  src/core/activity/activityChart/activityChartPanelModels/spikeTimesHistogramModel.ts
  src/core/activity/activityChart/activityChartPanelModels/spikeTimesPanelModel.ts
  src/core/activity/activityChart/activityChartPanelModels/spikeTimesPlotModel.ts
  src/core/activity/activityChart/activityChartPanelModels/spikeTimesRasterPlotModel.ts
  src/core/activity/activityGraph.ts
  src/core/activity/analogSignalActivity.ts
  src/core/common/config.ts
  src/core/connection/connectionView.ts
  src/core/model/model.ts
  src/core/model/modelView.ts
  src/core/network/network.ts
  src/core/network/networkGraph/networkGraphNodeAddPanel.ts
  src/core/node/node.ts
  src/core/node/nodeCode.ts
  src/core/node/nodeGraph/nodeGraphShape.ts
  src/core/node/nodeRecord.ts
  src/core/node/nodeView.ts
  src/core/project/project.ts
  src/core/project/projectCode.ts
  src/core/project/projectUpgrade.ts
  src/views/Settings.vue
Labels: enhancement

#204 Lazy loading of projects
  src/components/activity/ActivityGraph.vue
  src/components/activity/ActivityGraphIcon.vue
  src/components/activity/activityChart/ActivityChartController.vue
  src/components/activity/activityChart/ActivityChartPanelToolbar.vue
  src/components/navigation/Navigation.vue
  src/components/navigation/ProjectNavList.vue
  src/components/project/ProjectsDialog.vue
  src/components/project/ProjectsMenu.vue
  src/core/activity/activityChart/activityChartGraph.ts
  src/core/project/project.ts
  src/core/project/projectStore.ts
  src/views/Project.vue
Labels: enhancement

#205 Docs about CI und deployment of Insite
  docs/deployer/deploy-insite.rst
  docs/developer/continuous-integration.rst
Labels: documentation

#206 Add files for Electron
  .gitignore
  icons/icon.png
  package.json
  singularity/ubuntu-nest-desktop-dev.def
  src/assets/config/NESTSimulator.json
  src/background.ts
  src/nest.ts
  src/router/index.ts
  tests/unit/electron.spec.js
  vue.config.js
  yarn.lock
Labels: enhancement

#208 Remove "dev" from version for gitlab-ci
  .gitlab-ci.yml
Labels: maintenance

#212 Upgrade node modules
  package.json
  yarn.lock
Labels: bug, maintenance

#210 Better config for electron-builder
  .gitlab-ci.yml
  electron-builder.yml
  package.json
  singularity/ubuntu-nest-desktop-dev.def
  vue.config.js
Labels: enhancement

#213 Build electron in GitLab CI.
  .gitlab-ci.yml
  singularity/ubuntu-nest-desktop-dev.def
Labels: bug

#214 Use electronuserland/builder:wine to build electron
  .gitlab-ci.yml
Labels: enhancement

#215 Add `-p never` for electron-builder
  package.json
Labels: maintenance

#217 Correct VERSION
  .gitlab-ci.yml
Labels: bug

#219 docker-runner for snap
  .gitlab-ci.yml
Labels: bug

#220 Add files for e2e test
  package.json
  src/views/AppInfo.vue
  tests/e2e/.eslintrc.js
  tests/e2e/custom-assertions/elementCount.js
  tests/e2e/custom-commands/customExecute.js
  tests/e2e/custom-commands/openHomepage.js
  tests/e2e/custom-commands/openHomepageClass.js
  tests/e2e/globals.js
  tests/e2e/page-objects/homepage.js
  tests/e2e/specs/test-with-pageobjects.js
  tests/e2e/specs/test.js
  yarn.lock
Labels: enhancement

#221 Doc: Introducing the first coding conventions
  docs/contents.rst
  docs/developer/coding-conventions.rst
Labels: documentation

#222 Shorten expire duration for electron artifacts
  .gitlab-ci.yml
Labels: maintenance

#223 Clean node modules
  package.json
  src/components/HelloWorld.vue
  tests/unit/electron.spec.js
  tests/unit/example.spec.ts
  yarn.lock
Labels: maintenance

#225 Structural overview I
  docs/_static/img/screenshots/program-overview_expanded.png
  docs/developer/interface-concept.rst
  docs/reference/structural-overview.rst
Labels: documentation

#209 Update docker-compose
  docker-compose.yml
Labels: maintenance

#228 Upgrade node modules
  package.json
  yarn.lock
Labels: maintenance

#229 Remove condition to show node record selected for table
  src/components/activity/activityStats/ActivityStatsAnalog.vue
Labels: maintenance

#230 Github-Workflow: Update name for ebrains-push.yml
  .github/workflows/ebrains-push.yml
Labels: discussion

#227 Update node record.
  src/components/activity/activityChart/ActivityChartController.vue
  src/components/node/NodeModelSelect.vue
  src/components/node/NodeParamEdit.vue
  src/components/parameter/ParameterEdit.vue
  src/core/activity/activityChart/activityChartPanelModel.ts
  src/core/activity/activityChart/activityChartPanelModels/analogSignalPanelModel.ts
  src/core/common/database.ts
  src/core/node/node.ts
  src/core/node/nodeRecord.ts
  src/core/project/projectStore.ts
Labels: bug

#231 Big Bang 9: Restructure activity animation graph
  package.json
  src/components/activity/activityAnimation/ActivityAnimationController.vue
  src/components/activity/activityAnimation/ActivityAnimationGraph.vue
  src/core/activity/activityAnimation/activityAnimationGraph.ts
  src/core/activity/activityAnimation/activityAnimationLayer.ts
  src/core/activity/activityAnimation/activityAnimationLayerModel.ts
  src/core/activity/activityAnimation/activityAnimationLayerModels/BoxGeometryLayerModel.ts
  src/core/activity/activityAnimation/activityAnimationLayerModels/SphereGeometryLayerModel.ts
  src/core/activity/activityAnimation/activityAnimationScene.ts
  src/core/activity/activityAnimation/activityAnimationScenes/activityAnimationSceneBox.ts
  src/core/activity/activityAnimation/activityAnimationScenes/activityAnimationSceneBoxHistogram.ts
  src/core/activity/activityAnimation/activityAnimationScenes/activityAnimationSceneSphere.ts
  src/core/activity/activityAnimation/activityAnimationScenes/activityScatterTimeAnimationScene.ts
  src/core/activity/activityChart/activityChartPanelModel.ts
  src/core/activity/activityGraph.ts
  src/core/node/nodeRecord.ts
  src/shims-vue.d.ts
  yarn.lock
Labels: enhancement

#233 Add and update singularity recipes
  singularity/dev-electron-builder.def
  singularity/dev-node-16-alpine.def
  singularity/doc-sphinx.def
  singularity/nest-desktop-prod.def
  singularity/prod-snapcraft.def
  singularity/test-ubuntu-20.04.def
Labels: maintenance

#234 Style panel for node positions
  src/components/node/NodePosition.vue
Labels: maintenance

#232 Clean docs
  docs/about/abstract.rst
  docs/about/history.rst
  docs/about/releases.rst
  docs/conf.py
  docs/contents.rst
  docs/deployer/deploy-docker-compose.rst
  docs/deployer/deploy-insite.rst
  docs/deployer/deploy-openshift.rst
  docs/deployer/deploy-openstack.rst
  docs/deployer/index.rst
  docs/developer/coding-conventions.rst
  docs/developer/continuous-integration.rst
  docs/developer/development.rst
  docs/developer/index.rst
  docs/developer/preparation.rst
  docs/developer/production.rst
  docs/developer/semantic-version.rst
  docs/developer/user-doc.rst
  docs/reference/structural-overview.rst
  docs/user/setup.rst
  docs/user/usage.rst
Labels: documentation

#235 Change button style for deleting node
  src/components/node/NodePopMenu.vue
Labels: maintenance

#236 Upgrade node modules
  package.json
  yarn.lock
Labels: maintenance

#238 Upgrade version of NEST UserDoc
  src/components/model/ModelDocumentation.vue
Labels: maintenance

#239 Fix double showing of text
  src/core/model/modelView.ts
Labels: bug

#240 Rename image names for logo
  src/assets/img/logo/nest-desktop-logo-dark.svg
  src/assets/img/logo/nest-desktop-logo-light.svg
  src/assets/img/logo/nest-desktop-logo.png
  src/views/AppInfo.vue
Labels: maintenance

#237 Restyle docs
  docs/_static/css/bootstrap.min.css
  docs/_static/css/bootstrap.min.css.map
  docs/_static/css/styles.css
  docs/_static/img/icons/apple.svg
  docs/_static/img/icons/linux.svg
  docs/_static/img/icons/user-cog.svg
  docs/_static/img/icons/user-edit.svg
  docs/_static/img/icons/user-gear.svg
  docs/_static/img/icons/user-graduate.svg
  docs/_static/img/icons/user-pen.svg
  docs/_static/img/icons/user.svg
  docs/_static/img/icons/windows.svg
  docs/_static/img/installation-guide.png
  docs/_static/img/logo/nest-desktop-logo.png
  docs/_static/img/nest/cloud-server-NEST.png
  docs/_static/img/nest/cloud-server-docker-NEST.png
  docs/_static/img/nest/docker-NEST.png
  docs/_static/img/nest/laptop-NEST.png
  docs/_static/img/nest/pc-NEST.png
  docs/_static/img/screenshots/start-page.png
  docs/_static/js/bootstrap.min.js
  docs/_static/js/bootstrap.min.js.map
  docs/_templates/layout.html
  docs/about/history.rst
  docs/conf.py
  docs/contents.rst
  docs/deployer/deploy-insite.rst
  docs/deployer/index.rst
  docs/developer/index.rst
  docs/favicon.ico
  docs/index.rst
  docs/lecturer/course-protocol.rst
  docs/lecturer/didactic-concept.rst
  docs/lecturer/first-steps.rst
  docs/lecturer/index.rst
  docs/user/index.rst
  docs/user/troubleshooting.rst
Labels: documentation

#242 Fix broken link in readme
  README.md
Labels: bug

#243 Correct port-binding for nest-desktop service
  docker-compose.yml
Labels: bug

#244 Fix initializing activity graph for connection/model changes.
  src/core/activity/activityChart/activityChartGraph.ts
  src/core/activity/activityChart/activityChartPanelModel.ts
  src/core/activity/activityGraph.ts
  src/core/connection/connection.ts
  src/core/network/network.ts
  src/core/node/node.ts
Labels: bug

#245 Update message for consoleLog
  src/core/model/modelStore.ts
  src/core/project/projectStore.ts
Labels: maintenance

#247 Use hash for router history
  src/router/index.ts
Labels: bug

#248 Rename var for project
  src/views/Project.vue
Labels: maintenance

#249 Add guide how to use and deploy Insite
  docs/_static/img/screenshots/settings-insite.png
  docs/_static/img/screenshots/simulate-with-insite.png
  docs/deployer/deploy-insite.rst
  docs/user/usage-insite.rst
Labels: documentation

#246 Enhance docker
  .dockerignore
  .gitignore
  .gitlab-ci.yml
  docker/Dockerfile
  docker/Dockerfile-builder
  docker/nginx-default.conf
  nest_desktop/__init__.py
Labels: maintenance

#252 Better width of selection in import model dialog
  src/components/model/ModelsImport.vue
Labels: maintenance

#254 Code break in lecturerDocs
  docs/lecturer/bachelor/single-neuron-direct-current-injection.rst
  docs/lecturer/bachelor/single-neuron-noise-current-injection.rst
  docs/lecturer/bachelor/single-neuron-poisson-input.rst
  docs/lecturer/bachelor/single-neuron-synaptic-input.rst
  docs/lecturer/course-design.rst
  docs/lecturer/course-protocol.rst
  docs/lecturer/didactic-concept.rst
  docs/lecturer/doctorate/networks-decision-making.rst
  docs/lecturer/first-steps.rst
  docs/lecturer/index.rst
  docs/lecturer/master/hodgkin-huxley-action-potential.rst
  docs/lecturer/master/network-dynamics.rst
  docs/lecturer/master/point-neuron-conductance.rst
Labels: documentation

#251 Add userDoc for NEST models
  docs/_static/img/screenshots/explore-models.png
  docs/_static/img/screenshots/model-activity-explorer.png
  docs/_static/img/screenshots/model-activity.png
  docs/_static/img/screenshots/model-documentation.png
  docs/_static/img/screenshots/model-editor.png
  docs/_static/img/screenshots/model-nav.png
  docs/_static/img/screenshots/models-filter-tag.png
  docs/_static/img/screenshots/models-import.png
  docs/_static/img/screenshots/models-menu.png
  docs/contents.rst
  docs/user/index.rst
  docs/user/nest-models.rst
  docs/user/usage.rst
Labels: documentation
