Repository nest-desktop/nest-desktop, pull requests merged in 2022-02, with the labels that each got.

#256 Fix format error for CI
  .gitlab-ci.yml
Labels: bug

#257 Update .gitlab-ci.yml
  .gitlab-ci.yml
Labels: bug

#258 Update .gitlab-ci.yml
  .gitlab-ci.yml
Labels: bug

#255 Update config for docs
  docs/_static/favicon.ico
  docs/_templates/layout.html
  docs/conf.py
Labels: documentation

#259 Upgrade node modules
  package.json
  yarn.lock
Labels: maintenance

#261 Remove smooth scroll
  docs/_static/css/styles.css
Labels: maintenance

#241 Add axios instances, combineURLS and slash suffix in URL for Insite
  docker/Dockerfile
  docker/Dockerfile-builder
  docker/entrypoint.sh
  public/config.json
  src/App.vue
  src/assets/codemirror/addon/hint/pyNEST-hint.js
  src/assets/config/InsiteAccess.json
  src/assets/config/NESTSimulator.json
  src/components/setting/InsiteAccessConfig.vue
  src/components/setting/NESTSimulatorConfig.vue
  src/core/activity/analogSignalActivity.ts
  src/core/activity/spikeActivity.ts
  src/core/app.ts
  src/core/common/backend.ts
  src/core/model/model.ts
  src/core/model/modelStore.ts
  src/core/model/modelView.ts
  src/core/project/project.ts
  src/main.ts
  src/shims-vue.d.ts
Labels: enhancement

#260 Fix bug to import model from github
  src/components/model/ModelMenu.vue
  src/components/model/ModelsImport.vue
  src/components/navigation/ModelNavList.vue
  src/core/model/modelStore.ts
Labels: bug

#264 Add types for function returns
  src/core/activity/activityAnimation/activityAnimationLayer.ts
  src/core/activity/activityAnimation/activityAnimationScene.ts
  src/core/connection/connectionGraph/connectionGraph.ts
  src/core/connection/connectionMask.ts
  src/core/network/networkGraph/networkGraph.ts
  src/core/network/networkGraph/networkGraphDragline.ts
  src/core/network/networkGraph/networkGraphGrid.ts
  src/core/node/nodeGraph/nodeGraph.ts
  src/core/node/nodeGraph/nodeGraphShape.ts
  src/core/node/nodeSpatial/nodeSpatial.ts
  src/core/parameter/numeric.ts
  src/nest.ts
Labels: maintenance

#265 Sort args and prettier codes
  public/index.html
  src/components/activity/ActivityGraph.vue
  src/components/activity/activityAnimation/ActivityAnimationController.vue
  src/components/activity/activityChart/ActivityChartController.vue
  src/components/activity/activityStats/ActivityStatsAnalog.vue
  src/components/activity/activityStats/ActivityStatsSpike.vue
  src/components/connection/ConnectionMenu.vue
  src/components/connection/ConnectionParamEdit.vue
  src/components/connection/ConnectionParamSelect.vue
  src/components/icons/DiceMultipleOutlineIcon.vue
  src/components/icons/DotsGridIcon.vue
  src/components/icons/NESTIcon.vue
  src/components/model/ModelDocumentation.vue
  src/components/model/ModelEditor.vue
  src/components/model/ModelMenu.vue
  src/components/model/ModelsDialog.vue
  src/components/model/ModelsImport.vue
  src/components/model/ModelsMenu.vue
  src/components/navigation/ModelNavList.vue
  src/components/navigation/Navigation.vue
  src/components/navigation/ProjectNavList.vue
  src/components/network/NetworkEditor.vue
  src/components/network/NetworkEditorToolbar.vue
  src/components/network/NetworkParamEdit.vue
  src/components/node/NodeMenu.vue
  src/components/node/NodeParamEdit.vue
  src/components/node/NodePopMenu.vue
  src/components/node/NodePosition.vue
  src/components/node/NodePositionTitle.vue
  src/components/parameter/ParameterEdit.vue
  src/components/parameter/ParameterEditExpert.vue
  src/components/project/ProjectLabBook.vue
  src/components/project/ProjectsDialog.vue
  src/components/project/ProjectsImport.vue
  src/components/setting/InsiteAccessConfig.vue
  src/components/setting/NESTSimulatorConfig.vue
  src/components/setting/SettingsMenu.vue
  src/components/simulation/SimulationCodeEditor.vue
  src/components/simulation/SimulationKernel.vue
Labels: maintenance

#262 Add docs for activity graph
  docs/_static/img/screenshots/activity-anim-graph-analog.png
  docs/_static/img/screenshots/activity-anim-graph-spike.png
  docs/_static/img/screenshots/activity-chart-graph-analog.png
  docs/_static/img/screenshots/activity-chart-graph-spike.png
  docs/contents.rst
  docs/user/activity-graph.rst
  docs/user/index.rst
Labels: documentation

#263 Restyle docs and link to paragraphs
  docs/about/releases.rst
  docs/deployer/deploy-docker-compose.rst
  docs/deployer/deploy-openshift.rst
  docs/deployer/deploy-openstack.rst
  docs/developer/coding-conventions.rst
  docs/developer/command-API.rst
  docs/developer/continuous-integration.rst
  docs/developer/development.rst
  docs/developer/interface-concept.rst
  docs/developer/preparation.rst
  docs/developer/production.rst
  docs/developer/user-doc.rst
  docs/user/setup.rst
  docs/user/troubleshooting.rst
  docs/user/usage-insite.rst
  docs/user/usage.rst
Labels: documentation

#266 Update license
  LICENSE
  docs/conf.py
Labels: maintenance

#274 Use latest Sphinx version and packages
  .readthedocs.yaml
  .readthedocs.yml
  docs/conf.py
  docs/environment.yaml
  docs/requirements.txt
  package.json
Labels: maintenance

#276 Correct ref that makes RTD broken
  docs/user/usage-insite.rst
Labels: bug

#267 Upgrade node modules, change dev stage
  package.json
  yarn.lock
Labels: maintenance

#268 Fix record showing if no V_M
  src/core/activity/activityAnimation/activityAnimationLayer.ts
  src/core/project/project.ts
Labels: bug

#272 Change log scale for histogram
  src/core/activity/activityChart/activityChartPanelModels/spikeTimesHistogramModel.ts
Labels: maintenance

#273 Dev and dark mode button
  src/components/navigation/Navigation.vue
Labels: maintenance

#278 Fix scroll behavior in lab book
  src/components/project/ProjectLabBook.vue
Labels: bug

#271 Correct intention for node blocks
  docs/deployer/deploy-openshift.rst
  docs/developer/development.rst
  docs/lecturer/bachelor/single-neuron-poisson-input.rst
  docs/lecturer/doctorate/networks-decision-making.rst
  docs/lecturer/index.rst
  docs/lecturer/master/network-dynamics.rst
  docs/user/nest-models.rst
  docs/user/setup.rst
  docs/user/troubleshooting.rst
  docs/user/usage-insite.rst
  docs/user/usage.rst
  docs/user/use-ebrains.rst
Labels: documentation

#280 Enhance activity graph with data for each sender
  src/components/parameter/ParameterEdit.vue
  src/core/activity/activityChart/activityChartPanel.ts
  src/core/activity/activityChart/activityChartPanelModels/CVISIHistogramModel.ts
  src/core/activity/activityChart/activityChartPanelModels/analogSignalHistogramModel.ts
  src/core/activity/activityChart/activityChartPanelModels/analogSignalPanelModel.ts
  src/core/activity/activityChart/activityChartPanelModels/analogSignalPlotModel.ts
  src/core/activity/activityChart/activityChartPanelModels/interSpikeIntervalHistogramModel.ts
  src/core/activity/activityChart/activityChartPanelModels/senderCVISIPlotModel.ts
  src/core/activity/activityChart/activityChartPanelModels/senderMeanISIPlotModel.ts
  src/core/activity/activityChart/activityChartPanelModels/senderSpikeCountPlotModel.ts
  src/core/activity/activityChart/activityChartPanelModels/spikeSendersHistogramModel.ts
  src/core/activity/activityChart/activityChartPanelModels/spikeTimesHistogramModel.ts
  src/core/activity/activityChart/activityChartPanelModels/spikeTimesPanelModel.ts
  src/core/activity/activityChart/activityChartPanelModels/spikeTimesRasterPlotModel.ts
Labels: enhancement

#281 Add F-I curve for neuron models
  src/assets/projects/model-f-i-curve.json
  src/core/model/modelView.ts
  src/views/Model.vue
Labels: enhancement

#269 Fix deleting projects and models
  src/core/model/model.ts
  src/core/project/project.ts
  src/core/project/projectDB.ts
  src/core/project/projectStore.ts
Labels: bug

#283 Remove parseFloat
  src/core/parameter/parameter.ts
Labels: bug

#286 Upgrade node modules
  package.json
  yarn.lock
Labels: maintenance

#284 Run docker container as non-user
  docker-compose.yml
  docker/Dockerfile
  docker/Dockerfile-builder
  docker/nginx-default.conf
Labels: maintenance

#287 Add events for plot visiblity
  src/core/activity/activityChart/activityChartGraph.ts
  src/core/activity/activityChart/activityChartPanelModel.ts
  src/core/activity/activityChart/activityChartPanelModels/CVISIHistogramModel.ts
  src/core/activity/activityChart/activityChartPanelModels/FICurvePlotModel.ts
  src/core/activity/activityChart/activityChartPanelModels/analogSignalHistogramModel.ts
  src/core/activity/activityChart/activityChartPanelModels/analogSignalPlotModel.ts
  src/core/activity/activityChart/activityChartPanelModels/interSpikeIntervalHistogramModel.ts
  src/core/activity/activityChart/activityChartPanelModels/senderCVISIPlotModel.ts
  src/core/activity/activityChart/activityChartPanelModels/senderMeanISIPlotModel.ts
  src/core/activity/activityChart/activityChartPanelModels/senderSpikeCountPlotModel.ts
  src/core/activity/activityChart/activityChartPanelModels/spikeTimesHistogramModel.ts
  src/core/activity/activityChart/activityChartPanelModels/spikeTimesRasterPlotModel.ts
Labels: enhancement

#289 Update static for docs
  docs/_static/img/screenshots/activity-explorer.png
  docs/_static/img/screenshots/kernel-settings.png
  docs/_static/img/screenshots/network-editor.png
  docs/_static/img/screenshots/program-overview_expanded.png
  docs/developer/interface-concept.rst
  docs/reference/structural-overview.rst
  docs/user/usage.rst
Labels: documentation

#291 Docs: Add hint how to prevent freezes during compilation
  docs/developer/preparation.rst
Labels: documentation

#292 Docs reference model about
  docs/reference/sections/about.rst
  docs/reference/sections/model.rst
Labels: documentation

#295 Upgrade node modules
  package.json
  yarn.lock
Labels: maintenance

#297 Fix showing correct activity chart when resizing
  src/components/activity/activityChart/ActivityChartGraph.vue
  src/core/activity/activityChart/activityChartGraph.ts
Labels: bug

#298 Sort imported functions
  src/components/CodeMirror.vue
  src/components/activity/ActivityGraphIcon.vue
  src/components/activity/activityAnimation/ActivityAnimationGraph.vue
  src/components/activity/activityChart/ActivityChartController.vue
  src/components/activity/activityChart/ActivityChartPanelToolbar.vue
  src/components/connection/ConnectionMenu.vue
  src/components/connection/ConnectionParamEdit.vue
  src/components/connection/ConnectionParamSelect.vue
  src/components/model/ModelEditor.vue
  src/components/model/ModelMenu.vue
  src/components/model/ModelsImport.vue
  src/components/navigation/ModelNavList.vue
  src/components/network/NetworkEditor.vue
  src/components/network/NetworkParamEdit.vue
  src/components/node/NodeMenu.vue
  src/components/node/NodeModelSelect.vue
  src/components/node/NodeParamEdit.vue
  src/components/node/NodePopMenu.vue
  src/components/node/NodePosition.vue
  src/components/project/ProjectsImport.vue
  src/components/simulation/SimulationButton.vue
  src/components/simulation/SimulationCodeEditor.vue
  src/components/simulation/SimulationKernel.vue
  src/components/synapse/SynapseModelSelect.vue
  src/components/synapse/SynapseParamEdit.vue
  src/components/synapse/SynapseParamSelect.vue
Labels: maintenance

#301 Do not run job for tags
  .gitlab-ci.yml
Labels: enhancement

#304 Correct rules
  .gitlab-ci.yml
Labels: bug

#299 Add job for nestsim/nest-desktop
  .gitlab-ci.yml
Labels: enhancement

#303 Correct releases
  docs/about/releases.rst
Labels: documentation

#305 Remove bracket
  docs/deployer/deploy-docker-compose.rst
Labels: documentation

#307 Remove when always in deploy stages
  .gitlab-ci.yml
Labels: maintenance

#306 Update badge for docker-hub on README
  README.md
  docs/index.rst
Labels: maintenance

#308 Patch to v3.1.1
  .gitlab-ci.yml
  README.md
  docs/about/releases.rst
  docs/deployer/deploy-docker-compose.rst
  docs/index.rst
  package.json
  src/components/CodeMirror.vue
  src/components/activity/ActivityGraphIcon.vue
  src/components/activity/activityAnimation/ActivityAnimationGraph.vue
  src/components/activity/activityChart/ActivityChartController.vue
  src/components/activity/activityChart/ActivityChartGraph.vue
  src/components/activity/activityChart/ActivityChartPanelToolbar.vue
  src/components/connection/ConnectionMenu.vue
  src/components/connection/ConnectionParamEdit.vue
  src/components/connection/ConnectionParamSelect.vue
  src/components/model/ModelEditor.vue
  src/components/model/ModelMenu.vue
  src/components/model/ModelsImport.vue
  src/components/navigation/ModelNavList.vue
  src/components/network/NetworkEditor.vue
  src/components/network/NetworkParamEdit.vue
  src/components/node/NodeMenu.vue
  src/components/node/NodeModelSelect.vue
  src/components/node/NodeParamEdit.vue
  src/components/node/NodePopMenu.vue
  src/components/node/NodePosition.vue
  src/components/project/ProjectsImport.vue
  src/components/simulation/SimulationButton.vue
  src/components/simulation/SimulationCodeEditor.vue
  src/components/simulation/SimulationKernel.vue
  src/components/synapse/SynapseModelSelect.vue
  src/components/synapse/SynapseParamEdit.vue
  src/components/synapse/SynapseParamSelect.vue
  src/core/activity/activityChart/activityChartGraph.ts
  yarn.lock
Labels: bug

#290 Add toolbar for code editor and download codes
  package.json
  src/assets/config/ProjectView.json
  src/components/activity/ActivityGraph.vue
  src/components/simulation/SimulationButton.vue
  src/components/simulation/SimulationCodeEditor.vue
  src/core/network/networkCode.ts
  src/core/node/nodeCode.ts
  src/core/project/project.ts
  src/core/project/projectCode.ts
  src/core/project/projectUpgrade.ts
  src/core/project/projectView.ts
  src/views/Model.vue
  src/views/Project.vue
  yarn.lock
Labels: enhancement

#314 Patch v3.1.2
  docs/about/releases.rst
  package.json
  src/components/navigation/ModelNavList.vue
  src/core/activity/activityChart/activityChartPanelModels/CVISIHistogramModel.ts
  src/core/activity/activityChart/activityChartPanelModels/FICurvePlotModel.ts
  src/core/activity/activityChart/activityChartPanelModels/interSpikeIntervalHistogramModel.ts
  src/core/activity/activityChart/activityChartPanelModels/senderCVISIPlotModel.ts
  src/core/activity/activityChart/activityChartPanelModels/senderMeanISIPlotModel.ts
  src/core/activity/activityChart/activityChartPanelModels/senderSpikeCountPlotModel.ts
  src/core/activity/activityChart/activityChartPanelModels/spikeTimesHistogramModel.ts
  src/core/activity/activityChart/activityChartPanelModels/spikeTimesRasterPlotModel.ts
  src/core/model/modelView.ts
Labels: bug
