Repository nest-desktop/nest-desktop, pull requests merged in 2022-03, with the labels that each got.

#315 Node modules
  package.json
  src/main.ts
  src/nest.ts
  src/store/index.ts
  yarn.lock
Labels: dependencies

#316 Upgrade vue cli 5
  babel.config.js
  bin/nest-desktop
  package.json
  src/environments/environment.prod.ts
  src/environments/environment.ts
  vue.config.js
  yarn.lock
Labels: dependencies

#321 Extend the documentation with some missing parts of v3.1
  docs/contents.rst
  docs/developer/continuous-integration.rst
  docs/developer/index.rst
  docs/developer/production.rst
  docs/developer/semantic-version.rst
  docs/lecturer/index.rst
  docs/user/usage.rst
Labels: documentation

#322 Remove iframe
  src/App.vue
Labels: maintenance

#323 Fix checkbox node color
  src/components/node/NodeModelSelect.vue
Labels: bug

#326 Fix scroll behavior in model defaults
  src/views/Model.vue
Labels: bug

#325 Use const
  src/components/parameter/ParameterEdit.vue
Labels: maintenance

#330 Docs: Use headings
  docs/about/abstract.rst
  docs/about/history.rst
  docs/deployer/deploy-docker-compose.rst
  docs/deployer/deploy-openshift.rst
  docs/deployer/deploy-openstack.rst
  docs/developer/coding-conventions.rst
  docs/developer/command-API.rst
  docs/developer/development.rst
  docs/developer/index.rst
  docs/developer/interface-concept.rst
  docs/developer/preparation.rst
  docs/developer/production.rst
  docs/developer/semantic-version.rst
  docs/developer/user-doc.rst
  docs/index.rst
  docs/lecturer/bachelor/index.rst
  docs/lecturer/bachelor/single-neuron-direct-current-injection.rst
  docs/lecturer/bachelor/single-neuron-synaptic-input.rst
  docs/lecturer/course-protocol.rst
  docs/lecturer/doctorate/index.rst
  docs/lecturer/index.rst
  docs/lecturer/master/index.rst
  docs/lecturer/master/network-dynamics.rst
  docs/user/activity-graph.rst
  docs/user/index.rst
  docs/user/nest-models.rst
  docs/user/setup.rst
  docs/user/troubleshooting.rst
  docs/user/usage-insite.rst
  docs/user/usage.rst
  docs/user/use-ebrains.rst
Labels: documentation, discussion
