Repository nest-desktop/nest-desktop, pull requests merged in 2023-01, with the labels that each got.

#494 Upgrade node modules
  package.json
  yarn.lock
Labels: dependencies

#495 Fix synapse weight
  src/core/synapse/synapse.ts
Labels: bug

#496 Remove obsolete binding
  src/components/navigation/Navigation.vue
Labels: bug

#497 Fix style for NodeMenu and add option to activate HTTPS + HTTP/2 on dev server
  src/components/node/NodeMenu.vue
  vue.config.js
Labels: bug, enhancement

#498 Upgrade node modules
  yarn.lock
Labels: dependencies

#506 Fix error whether it is a string
  src/components/parameter/ParameterEdit.vue
  src/core/parameter/parameter.ts
Labels: bug

#507 Add plot model for firing rate
  src/components/parameter/ParameterEdit.vue
  src/core/activity/activityChart/activityChartGraph.ts
  src/core/activity/activityChart/activityChartPanelModels/senderCVISIPlotModel.ts
  src/core/activity/activityChart/activityChartPanelModels/senderMeanISIPlotModel.ts
  src/core/activity/activityChart/activityChartPanelModels/senderSpikeCountPlotModel.ts
  src/core/activity/activityChart/activityChartPanelModels/spikeCountPlotModel.ts
Labels: enhancement

#511 Fix reload loops when user wants to create a new project
  src/components/navigation/ProjectNavList.vue
  src/views/Project.vue
Labels: bug
