Repository nest-desktop/nest-desktop, pull requests merged in 2023-02, with the labels that each got.

#499 Upgrade projects
  src/assets/projects/current-input.json
  src/assets/projects/model-current-steps.json
  src/assets/projects/model-f-i-curve.json
  src/assets/projects/model-poisson-spikes-steps.json
  src/assets/projects/model-regular-spikes-steps.json
  src/assets/projects/model-spikes-up-down.json
  src/assets/projects/model-step-current-up-down.json
  src/assets/projects/spatial-neurons.json
  src/assets/projects/spatial-spike-activity.json
  src/assets/projects/spike-activity.json
  src/assets/projects/spike-input.json
Labels: maintenance

#501 Rename AppId and nest-server in electron
  electron-builder.yml
  src/background.ts
  src/nest-server.ts
Labels: maintenance

#502 Upgrade node modules
  package.json
  yarn.lock
Labels: dependencies

#503 Update year in license
  LICENSE
Labels: maintenance

#513 Fix clientWidth in anim graph
  src/core/activity/activityAnimation/activityAnimationScene.ts
Labels: bug

#508 Add '@vue/eslint-config-prettier' dependency
  package.json
  yarn.lock
Labels: dependencies

#516 Upgrade node modules
  yarn.lock
Labels: dependencies

#504 Upgrade default port for insite
  src/core/app.ts
Labels: maintenance

#517 Use node 16 to build
  docker/Dockerfile-builder
Labels: maintenance

#522 Update README
  README.md
Labels: maintenance

#519 Fix regex match for number
  src/components/parameter/ParameterEdit.vue
Labels: bug

#500 Add more PyNEST keywords
  src/assets/codemirror/addon/hint/pyNEST-keywords.ts
Labels: maintenance

#515 Update insite port
  src/assets/config/InsiteAccess.json
  src/assets/config/NESTSimulator.json
  src/components/setting/InsiteAccessConfig.vue
  src/core/app.ts
  src/main.ts
  src/views/Project.vue
Labels: maintenance

#520 Electron builder deb
  electron-builder.yml
  icons/icon.png
  package.json
  src/App.vue
Labels: maintenance

#525 Update year in doc conf
  docs/conf.py
Labels: documentation

#528 Update releases in doc
  docs/about/releases.rst
Labels: documentation

#526 Update events in doc
  docs/about/events.rst
Labels: documentation

#527 Doc index
  docs/index.rst
Labels: documentation

#529 Doc setup
  docs/user/setup/appimage.rst
  docs/user/setup/apptainer.rst
  docs/user/setup/conda.rst
  docs/user/setup/docker-compose.rst
  docs/user/setup/index.rst
  docs/user/setup/python.rst
  docs/user/setup/snap.rst
Labels: documentation

#530 Upgrade node modules
  package.json
  yarn.lock
Labels: dependencies

#531 Maintain electron builder
  electron-builder.yml
Labels: maintenance

#532 Update production doc
  docs/developer/stages/production.rst
Labels: documentation

#535 Remove electron build and snap in GitLab CI
  .gitlab-ci.yml
Labels: maintenance
