Repository nest-desktop/nest-desktop, pull requests merged in 2023-03, with the labels that each got.

#536 Docs: Fix typo in heading
  docs/reference/sections/project.rst
  docs/troubleshootings/network.rst
  docs/user/index.rst
  docs/user/setup/conda.rst
  docs/user/setup/python.rst
  docs/user/templates/usage-advanced.html
  docs/user/usage-advanced/activity-animation-graph.rst
  docs/user/usage-advanced/activity-chart-graph.rst
  docs/user/usage-advanced/command-API.rst
  docs/user/usage-advanced/compartmental-neuron.rst
  docs/user/usage-advanced/controller-sidebar.rst
  docs/user/usage-advanced/copy-model.rst
  docs/user/usage-advanced/model-view.rst
  docs/user/usage-advanced/network-graph.rst
  docs/user/usage-advanced/project-view.rst
  docs/user/usage-advanced/synapse-model.rst
  docs/user/usage-basic/explore-activity.rst
Labels: bug, documentation

#537 Upgrade node modules
  package.json
  yarn.lock
Labels: dependencies

#539 Introduce node annotation
  src/components/network/NetworkParamEdit.vue
  src/components/node/NodeAnnotations.vue
  src/core/network/network.ts
  src/core/network/networkState.ts
  src/core/node/node.ts
  src/core/simulation/simulationCode.ts
  src/core/simulation/simulationCodes/nest-v3.4.code
Labels: enhancement

#540 Upgrade node modules
  package.json
  yarn.lock
Labels: dependencies

#549 Upgrade nodes and version bump
  package.json
  yarn.lock
Labels: dependencies
